"""
LeetHub README Generator
Generates a README.md grouped by LeetCode topics for your LeetHub GitHub repo.

Usage:
  python generate_readme.py --repo /path/to/your/leethub/repo
  python generate_readme.py --repo .   (if run from inside the repo)
"""

import os
import re
import json
import time
import argparse
import urllib.request
import urllib.error

LEETCODE_GRAPHQL = "https://leetcode.com/graphql"

def get_problem_topics(title_slug):
    """Fetch topics for a problem from LeetCode GraphQL API."""
    query = {
        "query": """
        query getQuestionDetail($titleSlug: String!) {
          question(titleSlug: $titleSlug) {
            title
            difficulty
            topicTags {
              name
            }
          }
        }
        """,
        "variables": {"titleSlug": title_slug}
    }
    data = json.dumps(query).encode("utf-8")
    req = urllib.request.Request(
        LEETCODE_GRAPHQL,
        data=data,
        headers={
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0",
            "Referer": "https://leetcode.com"
        }
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            result = json.loads(resp.read().decode())
            q = result.get("data", {}).get("question", {})
            if not q:
                return [], "Unknown", ""
            tags = [t["name"] for t in q.get("topicTags", [])]
            difficulty = q.get("difficulty", "Unknown")
            title = q.get("title", "")
            return tags, difficulty, title
    except Exception as e:
        print(f"  [warn] Could not fetch {title_slug}: {e}")
        return [], "Unknown", ""


def extract_slug(folder_name):
    """Extract title slug from folder name like '0075-sort-colors' → 'sort-colors'."""
    match = re.match(r"^\d+-(.+)$", folder_name)
    return match.group(1) if match else folder_name


def get_problem_folders(repo_path):
    """Find all numbered problem folders in the repo."""
    folders = []
    for name in sorted(os.listdir(repo_path)):
        full = os.path.join(repo_path, name)
        if os.path.isdir(full) and re.match(r"^\d{4}-", name):
            folders.append(name)
    return folders


DIFFICULTY_EMOJI = {
    "Easy": "🟢",
    "Medium": "🟡",
    "Hard": "🔴",
    "Unknown": "⚪"
}


def generate_readme(repo_path, output_path=None):
    folders = get_problem_folders(repo_path)
    if not folders:
        print("❌ No problem folders found. Make sure you're pointing to the right repo path.")
        return

    print(f"✅ Found {len(folders)} problems. Fetching topics from LeetCode...\n")

    topic_map = {}   # topic → list of (folder, title, difficulty, number)
    seen = {}        # slug → (title, difficulty, topics) cache

    for folder in folders:
        slug = extract_slug(folder)
        num_match = re.match(r"^(\d+)-", folder)
        num = num_match.group(1) if num_match else "0000"

        print(f"  Fetching: {folder}")

        if slug in seen:
            tags, difficulty, title = seen[slug]
        else:
            tags, difficulty, title = get_problem_topics(slug)
            seen[slug] = (tags, difficulty, title)
            time.sleep(0.5)  # be nice to LeetCode API

        if not title:
            title = slug.replace("-", " ").title()
        if not tags:
            tags = ["Uncategorized"]

        for tag in tags:
            topic_map.setdefault(tag, []).append({
                "folder": folder,
                "title": title,
                "difficulty": difficulty,
                "num": int(num)
            })

    # Sort topics alphabetically, problems by number within each topic
    sorted_topics = sorted(topic_map.keys())

    lines = []
    lines.append("# 📚 LeetCode Solutions\n")
    lines.append("> Auto-generated by [generate_readme.py](./generate_readme.py) | Synced via [LeetHub](https://github.com/nickvdyck/leethub)\n")
    lines.append("")

    # Table of contents
    lines.append("## 📌 Topics\n")
    for topic in sorted_topics:
        anchor = topic.lower().replace(" ", "-").replace("/", "").replace("(", "").replace(")", "")
        count = len(topic_map[topic])
        lines.append(f"- [{topic}](#{anchor}) `{count}`")
    lines.append("")

    # Stats
    total = len(folders)
    easy = sum(1 for v in seen.values() if v[1] == "Easy")
    medium = sum(1 for v in seen.values() if v[1] == "Medium")
    hard = sum(1 for v in seen.values() if v[1] == "Hard")
    lines.append(f"## 📊 Stats\n")
    lines.append(f"| Total | 🟢 Easy | 🟡 Medium | 🔴 Hard |")
    lines.append(f"|-------|---------|-----------|---------|")
    lines.append(f"| {total} | {easy} | {medium} | {hard} |")
    lines.append("")

    # Problems by topic
    lines.append("---\n")
    for topic in sorted_topics:
        lines.append(f"## {topic}\n")
        problems = sorted(topic_map[topic], key=lambda x: x["num"])
        for p in problems:
            emoji = DIFFICULTY_EMOJI.get(p["difficulty"], "⚪")
            lc_url = f"https://leetcode.com/problems/{extract_slug(p['folder'])}/"
            gh_link = f"[📁 Code](https://github.com/PurvaSarode03/DSA/tree/main/{p['folder']})"
            lines.append(f"- {emoji} [{p['title']}]({lc_url}) {gh_link}")
        lines.append("")

    readme_content = "\n".join(lines)

    out = output_path or os.path.join(repo_path, "README.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write(readme_content)

    print(f"\n✅ README.md generated at: {out}")
    print(f"   {total} problems across {len(sorted_topics)} topics")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate LeetCode README grouped by topic")
    parser.add_argument("--repo", default=".", help="Path to your LeetHub GitHub repo")
    parser.add_argument("--output", default=None, help="Custom output path for README.md")
    args = parser.parse_args()

    repo_path = os.path.abspath(args.repo)
    print(f"📂 Repo path: {repo_path}\n")
    generate_readme(repo_path, args.output)
